Starts with adding testing capabilities
agirton/webpack-init pull request #9
Opened 2016-12-05 17:29 UTC by pksjce

With ref to #8, I'm adding testing capability to facilitate future development.

2016-12-09 06:28 UTC, agirton requested changes
This is looking good! Thank you so much for starting this. Can you also add the jest commands to the NPM scripts to help make it easier when deploying a new build or testing updates?

2016-12-09 06:28 UTC, agirton commented on package.json
> +    "jest": "^17.0.3",
Nit: I like to keep my dependencies exact to help reduce install issues. Can you update so this is exact?

2016-12-09 06:28 UTC, agirton commented on src/handleAnswers.js
> +const createLoadersConfig = ({initialEntry ="", loaders = [], ...rest}) => ({
Nit: I prefer to use single quotes for consistency and it looks like you used default quotes above. Can you update this to be single quotes?

2016-12-09 11:30 UTC, pksjce commented
Thanks a ton for taking time out to review! Yeah. Have some time this month, so will try to focus on this :)

2016-12-11 17:02 UTC, agirton commented
Thanks again!

2016-12-11 17:02 UTC, merged